version: "3.9"

services:
  flask:
    build: .
    ports:
      - "6969:6969"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"